name: Martin Civan
markdown: kramdown
#permalink: /blogy/:title
collections:
  blogy:
    permalink: /blogy/:title
    output: true
  zadania:
    output: true
    permalink: /zadania/:title
plugins:
  - jekyll-sitemap
  - liquid_reading_time